In [1]:
import hands
import functions
import dds
import ctypes

Loaded lib <CDLL './libdds.so', handle 55bcd2ec8650 at 0x7eff58184128>


In [4]:
dds.SetMaxThreads(0)

tableDealPBN = dds.ddTableDealPBN()
table = dds.ddTableResults()
myTable = ctypes.pointer(table)
functions.PrintTable(myTable)


tableDealPBN.cards = hands.PBN[0]
res = dds.CalcDDtablePBN(tableDealPBN, myTable)

functions.PrintTable(myTable)


      North South East  West 
   NT     0     0     0     0
    S     0     0     0     0
    H     0     0     0     0
    D     0     0     0     0
    C     0     0     0     0

      North South East  West 
   NT     6     7     7     6
    S     5     5     6     5
    H     8     7     6     6
    D     5     7     6     6
    C     8     5     5     6



In [16]:
l = list(map(list,myTable.contents.resTable))
t = [[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]]
t[0][0] = l[0][4]
t[0][1] = l[2][4]
t[0][2] = l[1][4]
t[0][3] = l[3][4]
for suit in range(4):
    t[suit+1][0] = l[0][suit]
    t[suit+1][1] = l[2][suit]
    t[suit+1][2] = l[1][suit]
    t[suit+1][3] = l[3][suit]
print(t)



[[6, 7, 7, 6], [5, 5, 6, 5], [8, 7, 6, 6], [5, 7, 6, 6], [8, 5, 5, 6]]


In [8]:
import numpy as np



def gen(n):
    x = np.random.choice(range(52), 52)
    ns = x[:26]
    ew = x[26:]
    res = [ns for _ in range(n)]
    for l in res:
        res.extend(np.random.permutation(ew))
    return l


In [2]:
 x = np.random.choice(range(52), 52)

In [3]:
    ns = x[:26]
    ew = x[26:]

In [4]:
ns

array([33, 39,  5, 14, 24, 33, 16, 34, 44, 29, 28, 16, 35, 36, 45, 50, 48,
       31, 43, 14, 34,  0, 46, 33, 29, 21])

In [5]:
ew

array([14, 32,  0, 29, 10, 41, 29, 34, 26, 24, 40, 16, 31, 50, 50, 47, 19,
       26, 16, 13, 22, 21, 29, 35, 20, 12])

In [7]:
res = [ns for _ in range(4)]

In [9]:
for l in res:
    res.extend(np.random.permutation(ew))

KeyboardInterrupt: 

In [10]:
np.random.permutation(ew)

array([22, 16, 35, 40, 13, 32, 16, 34, 29, 47, 21, 24, 10, 26, 19, 26, 20,
       14,  0, 29, 12, 50, 29, 31, 50, 41])

In [11]:
res[0]

array([33, 39,  5, 14, 24, 33, 16, 34, 44, 29, 28, 16, 35, 36, 45, 50, 48,
       31, 43, 14, 34,  0, 46, 33, 29, 21])

In [12]:
res[0].extend

AttributeError: 'numpy.ndarray' object has no attribute 'extend'

In [13]:
np.extend

AttributeError: module 'numpy' has no attribute 'extend'

In [16]:
np.append(res[0], ew)

array([33, 39,  5, 14, 24, 33, 16, 34, 44, 29, 28, 16, 35, 36, 45, 50, 48,
       31, 43, 14, 34,  0, 46, 33, 29, 21, 14, 32,  0, 29, 10, 41, 29, 34,
       26, 24, 40, 16, 31, 50, 50, 47, 19, 26, 16, 13, 22, 21, 29, 35, 20,
       12])